// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================

//! Integration coverage for every public domain field wire value.

use qubit_model::Field;

/// Verifies every Java-compatible field wire name resolves to its matching
/// Rust variant and remains stable after a serialization round trip.
#[test]
fn test_field_wire_values_round_trip_for_every_declared_field() {
    let fields = [
        (Field::Action, "ACTION"),
        (Field::Actual, "ACTUAL"),
        (Field::ActualCredentialNumber, "ACTUAL_CREDENTIAL_NUMBER"),
        (Field::ActualCredentialType, "ACTUAL_CREDENTIAL_TYPE"),
        (Field::AddressDetail, "ADDRESS_DETAIL"),
        (Field::AddressLatitude, "ADDRESS_LATITUDE"),
        (Field::AddressLongitude, "ADDRESS_LONGITUDE"),
        (Field::AddressPostalcode, "ADDRESS_POSTALCODE"),
        (Field::AddressStreetId, "ADDRESS_STREET_ID"),
        (Field::AddressVerify, "ADDRESS_VERIFY"),
        (Field::Age, "AGE"),
        (Field::Altitude, "ALTITUDE"),
        (Field::App, "APP"),
        (Field::AppId, "APP_ID"),
        (Field::Avatar, "AVATAR"),
        (Field::Birthday, "BIRTHDAY"),
        (Field::Blood, "BLOOD"),
        (Field::Buyer, "BUYER"),
        (Field::BuyerId, "BUYER_ID"),
        (Field::CategoryId, "CATEGORY_ID"),
        (Field::ChangePassword, "CHANGE_PASSWORD"),
        (Field::Channel, "CHANNEL"),
        (Field::ChannelNumber, "CHANNEL_NUMBER"),
        (Field::City, "CITY"),
        (Field::CityId, "CITY_ID"),
        (Field::Client, "CLIENT"),
        (Field::Code, "CODE"),
        (Field::Comment, "COMMENT"),
        (Field::CompleteTime, "COMPLETE_TIME"),
        (Field::Cost, "COST"),
        (Field::Count, "COUNT"),
        (Field::Country, "COUNTRY"),
        (Field::CountryId, "COUNTRY_ID"),
        (Field::CreateTime, "CREATE_TIME"),
        (Field::CreatorId, "CREATOR_ID"),
        (Field::Credential, "CREDENTIAL"),
        (Field::CredentialNumber, "CREDENTIAL_NUMBER"),
        (Field::CredentialType, "CREDENTIAL_TYPE"),
        (Field::CredentialVerify, "CREDENTIAL_VERIFY"),
        (Field::Currency, "CURRENCY"),
        (Field::DeleterId, "DELETER_ID"),
        (Field::DeleteTime, "DELETE_TIME"),
        (Field::Description, "DESCRIPTION"),
        (Field::Dict, "DICT"),
        (Field::Discount, "DISCOUNT"),
        (Field::DiscountReason, "DISCOUNT_REASON"),
        (Field::District, "DISTRICT"),
        (Field::DistrictId, "DISTRICT_ID"),
        (Field::Education, "EDUCATION"),
        (Field::Email, "EMAIL"),
        (Field::EmailVerify, "EMAIL_VERIFY"),
        (Field::Encrypted, "ENCRYPTED"),
        (Field::Entity, "ENTITY"),
        (Field::ErrorCode, "ERROR_CODE"),
        (Field::ErrorMessage, "ERROR_MESSAGE"),
        (Field::ErrorParams, "ERROR_PARAMS"),
        (Field::ErrorType, "ERROR_TYPE"),
        (Field::Ethnic, "ETHNIC"),
        (Field::Expected, "EXPECTED"),
        (
            Field::ExpectedCredentialNumber,
            "EXPECTED_CREDENTIAL_NUMBER",
        ),
        (Field::ExpectedCredentialType, "EXPECTED_CREDENTIAL_TYPE"),
        (Field::ExpiredReason, "EXPIRED_REASON"),
        (Field::ExpiredTime, "EXPIRED_TIME"),
        (Field::Fullname, "FULLNAME"),
        (Field::Gender, "GENDER"),
        (Field::Guardian, "GUARDIAN"),
        (Field::HasChild, "HAS_CHILD"),
        (Field::HasMedicare, "HAS_MEDICARE"),
        (
            Field::HasMedicareOrSocialSecurity,
            "HAS_MEDICARE_OR_SOCIAL_SECURITY",
        ),
        (Field::HasSocialSecurity, "HAS_SOCIAL_SECURITY"),
        (Field::Height, "HEIGHT"),
        (Field::Host, "HOST"),
        (Field::Icon, "ICON"),
        (Field::Id, "ID"),
        (Field::Image, "IMAGE"),
        (Field::Incoming, "INCOMING"),
        (Field::Industry, "INDUSTRY"),
        (Field::Inventory, "INVENTORY"),
        (Field::InvoiceStatus, "INVOICE_STATUS"),
        (Field::Ip, "IP"),
        (Field::ItemId, "ITEM_ID"),
        (Field::Job, "JOB"),
        (Field::JobTitle, "JOB_TITLE"),
        (Field::LastActiveTime, "LAST_ACTIVE_TIME"),
        (Field::LastLoginFailures, "LAST_LOGIN_FAILURES"),
        (Field::LastLoginTime, "LAST_LOGIN_TIME"),
        (Field::Latitude, "LATITUDE"),
        (Field::Level, "LEVEL"),
        (Field::LoginTime, "LOGIN_TIME"),
        (Field::Longitude, "LONGITUDE"),
        (Field::ManufacturerId, "MANUFACTURER_ID"),
        (Field::Marriage, "MARRIAGE"),
        (Field::MedicareCity, "MEDICARE_CITY"),
        (Field::MedicareCityId, "MEDICARE_CITY_ID"),
        (Field::Mobile, "MOBILE"),
        (Field::MobileCityArea, "MOBILE_CITY_AREA"),
        (Field::MobileCountryArea, "MOBILE_COUNTRY_AREA"),
        (Field::MobileNumber, "MOBILE_NUMBER"),
        (Field::MobileVerify, "MOBILE_VERIFY"),
        (Field::Mode, "MODE"),
        (Field::ModifierId, "MODIFIER_ID"),
        (Field::ModifyTime, "MODIFY_TIME"),
        (Field::Multiple, "MULTIPLE"),
        (Field::Name, "NAME"),
        (Field::NeedDelivery, "NEED_DELIVERY"),
        (Field::NewCredentialNumber, "NEW_CREDENTIAL_NUMBER"),
        (Field::NewCredentialType, "NEW_CREDENTIAL_TYPE"),
        (Field::NewEmail, "NEW_EMAIL"),
        (Field::NewFullname, "NEW_FULLNAME"),
        (Field::NewMobile, "NEW_MOBILE"),
        (Field::Nickname, "NICKNAME"),
        (Field::Nullable, "NULLABLE"),
        (Field::Number, "NUMBER"),
        (Field::OldCredentialNumber, "OLD_CREDENTIAL_NUMBER"),
        (Field::OldCredentialType, "OLD_CREDENTIAL_TYPE"),
        (Field::OldEmail, "OLD_EMAIL"),
        (Field::OldFullname, "OLD_FULLNAME"),
        (Field::OldMobile, "OLD_MOBILE"),
        (Field::Operation, "OPERATION"),
        (Field::OperatorId, "OPERATOR_ID"),
        (Field::OrderId, "ORDER_ID"),
        (Field::OrderItem, "ORDER_ITEM"),
        (Field::OrderItemId, "ORDER_ITEM_ID"),
        (Field::OrderTitle, "ORDER_TITLE"),
        (Field::Organization, "ORGANIZATION"),
        (Field::OrganizationId, "ORGANIZATION_ID"),
        (Field::OrganizationName, "ORGANIZATION_NAME"),
        (Field::OriginId, "ORIGIN_ID"),
        (Field::Owner, "OWNER"),
        (Field::OwnerCode, "OWNER_CODE"),
        (Field::OwnerId, "OWNER_ID"),
        (Field::OwnerType, "OWNER_TYPE"),
        (Field::Paid, "PAID"),
        (Field::ParentId, "PARENT_ID"),
        (Field::Password, "PASSWORD"),
        (Field::Payable, "PAYABLE"),
        (Field::PayeeAccountId, "PAYEE_ACCOUNT_ID"),
        (Field::PayeeAltitude, "PAYEE_ALTITUDE"),
        (Field::PayeeCredentialNumber, "PAYEE_CREDENTIAL_NUMBER"),
        (Field::PayeeCredentialType, "PAYEE_CREDENTIAL_TYPE"),
        (Field::PayeeEmail, "PAYEE_EMAIL"),
        (Field::PayeeId, "PAYEE_ID"),
        (Field::PayeeIp, "PAYEE_IP"),
        (Field::PayeeLatitude, "PAYEE_LATITUDE"),
        (Field::PayeeLongitude, "PAYEE_LONGITUDE"),
        (Field::PayeeName, "PAYEE_NAME"),
        (Field::PayeePhone, "PAYEE_PHONE"),
        (Field::PayeePlatform, "PAYEE_PLATFORM"),
        (Field::PayeeType, "PAYEE_TYPE"),
        (Field::PayerAccountId, "PAYER_ACCOUNT_ID"),
        (Field::PayerAltitude, "PAYER_ALTITUDE"),
        (Field::PayerCredentialNumber, "PAYER_CREDENTIAL_NUMBER"),
        (Field::PayerCredentialType, "PAYER_CREDENTIAL_TYPE"),
        (Field::PayerEmail, "PAYER_EMAIL"),
        (Field::PayerId, "PAYER_ID"),
        (Field::PayerIp, "PAYER_IP"),
        (Field::PayerLatitude, "PAYER_LATITUDE"),
        (Field::PayerLongitude, "PAYER_LONGITUDE"),
        (Field::PayerName, "PAYER_NAME"),
        (Field::PayerPhone, "PAYER_PHONE"),
        (Field::PayerPlatform, "PAYER_PLATFORM"),
        (Field::PayerType, "PAYER_TYPE"),
        (Field::PayTime, "PAY_TIME"),
        (Field::PersonId, "PERSON_ID"),
        (Field::Phone, "PHONE"),
        (Field::PhoneArea, "PHONE_AREA"),
        (Field::PhoneCityArea, "PHONE_CITY_AREA"),
        (Field::PhoneCountryArea, "PHONE_COUNTRY_AREA"),
        (Field::PhoneNumber, "PHONE_NUMBER"),
        (Field::PhoneVerify, "PHONE_VERIFY"),
        (Field::Platform, "PLATFORM"),
        (Field::Postalcode, "POSTALCODE"),
        (Field::Predefined, "PREDEFINED"),
        (Field::PrescriptionId, "PRESCRIPTION_ID"),
        (Field::Price, "PRICE"),
        (Field::PrivateKey, "PRIVATE_KEY"),
        (Field::Privileges, "PRIVILEGES"),
        (Field::Product, "PRODUCT"),
        (Field::ProductionDate, "PRODUCTION_DATE"),
        (Field::ProductCode, "PRODUCT_CODE"),
        (Field::ProductCount, "PRODUCT_COUNT"),
        (Field::ProductCurrency, "PRODUCT_CURRENCY"),
        (Field::ProductDescription, "PRODUCT_DESCRIPTION"),
        (Field::ProductId, "PRODUCT_ID"),
        (Field::ProductImage, "PRODUCT_IMAGE"),
        (Field::ProductItem, "PRODUCT_ITEM"),
        (Field::ProductItemId, "PRODUCT_ITEM_ID"),
        (Field::ProductName, "PRODUCT_NAME"),
        (Field::ProductPrice, "PRODUCT_PRICE"),
        (Field::ProductQuality, "PRODUCT_QUALITY"),
        (Field::ProductSpecification, "PRODUCT_SPECIFICATION"),
        (Field::ProductUnit, "PRODUCT_UNIT"),
        (Field::ProviderApp, "PROVIDER_APP"),
        (Field::ProviderAppId, "PROVIDER_APP_ID"),
        (Field::Province, "PROVINCE"),
        (Field::ProvinceId, "PROVINCE_ID"),
        (Field::PushToken, "PUSH_TOKEN"),
        (Field::ReadOnly, "READ_ONLY"),
        (Field::RefundTime, "REFUND_TIME"),
        (Field::Religion, "RELIGION"),
        (Field::Role, "ROLE"),
        (Field::RsaPublicKey, "RSA_PUBLIC_KEY"),
        (Field::SaleEndDate, "SALE_END_DATE"),
        (Field::SaleStartDate, "SALE_START_DATE"),
        (Field::Scene, "SCENE"),
        (Field::SecurityKey, "SECURITY_KEY"),
        (Field::Seller, "SELLER"),
        (Field::SellerId, "SELLER_ID"),
        (Field::SexOrientation, "SEX_ORIENTATION"),
        (Field::ShippingCost, "SHIPPING_COST"),
        (Field::ShippingDemand, "SHIPPING_DEMAND"),
        (Field::ShippingMode, "SHIPPING_MODE"),
        (Field::ShippingNumber, "SHIPPING_NUMBER"),
        (Field::ShipTime, "SHIP_TIME"),
        (Field::SocialSecurityCity, "SOCIAL_SECURITY_CITY"),
        (Field::SocialSecurityCityId, "SOCIAL_SECURITY_CITY_ID"),
        (Field::Source, "SOURCE"),
        (Field::SourceId, "SOURCE_ID"),
        (Field::Specification, "SPECIFICATION"),
        (Field::State, "STATE"),
        (Field::Status, "STATUS"),
        (Field::Success, "SUCCESS"),
        (Field::TargetId, "TARGET_ID"),
        (Field::TargetType, "TARGET_TYPE"),
        (Field::Timestamp, "TIMESTAMP"),
        (Field::Title, "TITLE"),
        (Field::Token, "TOKEN"),
        (Field::TokenCreateTime, "TOKEN_CREATE_TIME"),
        (Field::TokenExpiredTime, "TOKEN_EXPIRED_TIME"),
        (Field::TotalDiscount, "TOTAL_DISCOUNT"),
        (Field::TotalPrice, "TOTAL_PRICE"),
        (Field::TransactionId, "TRANSACTION_ID"),
        (Field::Type, "TYPE"),
        (Field::Udid, "UDID"),
        (Field::Unit, "UNIT"),
        (Field::UploadId, "UPLOAD_ID"),
        (Field::Url, "URL"),
        (Field::User, "USER"),
        (Field::Username, "USERNAME"),
        (Field::UserId, "USER_ID"),
        (Field::ValidTime, "VALID_TIME"),
        (Field::Value, "VALUE"),
        (Field::Verify, "VERIFY"),
        (Field::VerifyCode, "VERIFY_CODE"),
        (Field::Weight, "WEIGHT"),
        (Field::OpenidType, "OPENID_TYPE"),
        (Field::Openid, "OPENID"),
        (Field::Question, "QUESTION"),
        (Field::ThirdpartyInsuranceId, "THIRDPARTY_INSURANCE_ID"),
        (Field::AccidentReason, "ACCIDENT_REASON"),
        (Field::PolicyNumber, "POLICY_NUMBER"),
        (Field::KinshipType, "KINSHIP_TYPE"),
        (Field::Claimant, "CLAIMANT"),
        (Field::AccidentDate, "ACCIDENT_DATE"),
        (Field::AccidentPlace, "ACCIDENT_PLACE"),
        (Field::AccidentDescription, "ACCIDENT_DESCRIPTION"),
        (Field::Account, "ACCOUNT"),
        (Field::AccountType, "ACCOUNT_TYPE"),
        (Field::Insured, "INSURED"),
        (Field::ClaimId, "CLAIM_ID"),
        (Field::ClaimMedicalId, "CLAIM_MEDICAL_ID"),
        (Field::ClaimInvoiceId, "CLAIM_INVOICE_ID"),
        (Field::InvoiceNumber, "INVOICE_NUMBER"),
        (Field::TreatmentDate, "TREATMENT_DATE"),
        (Field::Amount, "AMOUNT"),
        (Field::InvoiceList, "INVOICE_LIST"),
        (Field::FundPaidAmount, "FUND_PAID_AMOUNT"),
        (Field::SelfPaidAmount, "SELF_PAID_AMOUNT"),
        (Field::SelfCareAmount, "SELF_CARE_AMOUNT"),
        (Field::MedicareAmount, "MEDICARE_AMOUNT"),
        (Field::SeriousIllnessPaid, "SERIOUS_ILLNESS_PAID"),
        (
            Field::SeriousIllnessInsurancePaid,
            "SERIOUS_ILLNESS_INSURANCE_PAID",
        ),
        (Field::CivilAffairSubsidyPaid, "CIVIL_AFFAIR_SUBSIDY_PAID"),
        (Field::MessageKey, "MESSAGE_KEY"),
        (Field::PrimaryDiagnosis, "PRIMARY_DIAGNOSIS"),
        (Field::MedicalChargeName, "MEDICAL_CHARGE_NAME"),
    ];

    for (field, wire_value) in fields {
        assert_eq!(
            field.code(),
            wire_value.to_lowercase(),
            "field {wire_value} must preserve its source code"
        );
        let encoded = format!("\"{wire_value}\"");
        let decoded: Field = serde_json::from_str(&encoded)
            .expect("every declared field wire value must deserialize");
        assert_eq!(
            serde_json::to_string(&decoded).expect("every field must serialize"),
            encoded,
            "field {wire_value} must preserve its source wire value"
        );
    }
}
